[package]
name = "polymesh-runtime-testnet-v1"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Common
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../../common", default-features = false }
polymesh-runtime-common = {package = "polymesh-runtime-common", path = "../common", default-features = false}
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false }

# Our pallets
pallet-protocol-fee = { package = "pallet-protocol-fee", path = "../../protocol-fee", default-features = false }
pallet-group = { package = "pallet-group", path = "../../group", default-features = false }
pallet-identity = { package = "pallet-identity", path = "../../identity", default-features = false  }
pallet-balances = { package = "pallet-balances", path = "../../balances", default-features = false  }
pallet-asset = { package = "pallet-asset", path = "../../asset", default-features = false }
pallet-transaction-payment = { package = "pallet-transaction-payment", path = "../../transaction-payment", default-features = false  }
pallet-staking = { package = "pallet-staking", path = "../../staking", default-features = false  }
pallet-staking-reward-curve = { version = "2.0.0",  path = "../../staking/reward-curve", default-features = false  }
pallet-pips = { package = "pallet-pips", path = "../../pips", default-features = false  }
pallet-committee = { package = "pallet-committee", path = "../../committee", default-features = false }
pallet-multisig = { package = "pallet-multisig", path = "../../multisig", default-features = false }
pallet-treasury = { package = "pallet-treasury", path = "../../treasury", default-features = false }
pallet-settlement = { path = "../../settlement", default-features = false }
pallet-im-online = { package = "pallet-im-online",  path = "../../im-online", default-features = false }
pallet-group-rpc-runtime-api = { path = "../../group/rpc/runtime-api", default-features = false }
pallet-compliance-manager = { package = "pallet-compliance-manager",  path = "../../compliance-manager", default-features = false }
pallet-statistics = { package = "pallet-statistics",  path = "../../statistics", default-features = false }
pallet-utility = { path = "../../utility", default-features = false}

# RPC
node-rpc-runtime-api = { path = "../../../rpc/runtime-api", default-features = false }



pallet-identity-rpc-runtime-api = { package = "pallet-identity-rpc-runtime-api", path = "../../identity/rpc/runtime-api", default-features = false }
pallet-staking-rpc-runtime-api = { package = "pallet-staking-rpc-runtime-api", path = "../../staking/rpc/runtime-api", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { package = "pallet-transaction-payment-rpc-runtime-api", path = "../../transaction-payment/rpc/runtime-api", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { package = "pallet-protocol-fee-rpc-runtime-api", path = "../../protocol-fee/rpc/runtime-api", default-features = false }
pallet-compliance-manager-rpc-runtime-api = { package = "pallet-compliance-manager-rpc-runtime-api", path = "../../compliance-manager/rpc/runtime-api", default-features = false  }

# Others
chrono = { version = "0.4.11", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
log = { version = "0.4.8", default-features = false }
rand = { version = "0.7.3", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
safe-mix = { version = "1.0.1", default-features = false }
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true }
serde_json = { version = "1.0.48", default-features = false }
yaml-rust = { version = "0.4.3", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-serializer = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-version = { package = "sp-version", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-api = { package = "sp-api", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-consensus-babe = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-authority-discovery = { package = "sp-authority-discovery", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-phragmen = { package = "sp-phragmen", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

pallet-authorship = { package = "pallet-authorship", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-contracts = { package = "pallet-contracts", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-executive = { package = "frame-executive", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-finality-tracker = { package = "pallet-finality-tracker", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-grandpa = { package = "pallet-grandpa", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-indices = { package = "pallet-indices", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-offences = { package = "pallet-offences", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-session = { package = "pallet-session", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-sudo = { package = "pallet-sudo", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-babe = { package = "pallet-babe", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-authority-discovery = { package = "pallet-authority-discovery", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
ink_primitives = { git = "https://github.com/paritytech/ink", package = "ink_primitives", default-features = false }
hex-literal = "0.2.1"

[dev-dependencies]
test-client = { package = "substrate-test-runtime-client", git = "https://github.com/paritytech/substrate", rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8"}

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"rustc-hex/std",
	"serde_derive",
	"rand/std",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-version/std",
	"sp-consensus-babe/std",
	"sp-session/std",
	"sp-authority-discovery/std",
	"sp-phragmen/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-arithmetic/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"polymesh-runtime-common/std",
	"pallet-authorship/std",
	"pallet-contracts/std",
	"pallet-executive/std",
	"pallet-finality-tracker/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-group-rpc-runtime-api/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-protocol-fee-rpc-runtime-api/std",
	"pallet-identity-rpc-runtime-api/std",
	"pallet-staking-rpc-runtime-api/std",
	"pallet-compliance-manager-rpc-runtime-api/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-settlement/std",
	"pallet-authority-discovery/std",
	"pallet-babe/std",
	"pallet-pips/std",
	"pallet-committee/std",
	"pallet-multisig/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"polymesh-common-utilities/std",
	"pallet-balances/std",
	"pallet-identity/std",
	"pallet-protocol-fee/std",
	"pallet-asset/std",
	"pallet-compliance-manager/std",
	"pallet-statistics/std",
	"pallet-asset/runtime-benchmarks",
	"ink_primitives/std",
	"node-rpc-runtime-api/std",
]
