[package]
name = "pallet-multisig"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.104", default-features = false }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }

pallet-identity = { package = "pallet-identity", path = "../identity", default-features = false}
pallet-transaction-payment = { package = "pallet-transaction-payment", path = "../transaction-payment", default-features = false}
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../common", default-features = false}
polymesh-primitives = { package = "polymesh-primitives", path = "../../primitives", default-features = false}

frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
    "serde/std",
	"codec/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-system/std",
	"frame-support/std",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std",
    "pallet-transaction-payment/std",
	"pallet-identity/std",
]
