[package]
name = "node-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Our pallets
polymesh-primitives = { path = "../../primitives", default-features = false }
pallet-pips = { path = "../../pallets/pips", default-features = false  }

# Other
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-std = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"polymesh-primitives/std",
]
